### ISSUE TITLE
Only one row of thumbnails is shown in overview mode

### ISSUE THREAD

**Issue by nein09** [sul-dlss/iiifManifestLayouts#113]
Whenever I hit shift-K to go into overview mode, I see the canvas labels and borders where they should be, but there is only ever one row of thumbnails loaded:

![one-row-thumbs](https://cloud.githubusercontent.com/assets/547883/12242051/9a905f8a-b84b-11e5-9c2d-dd7e198e71a7.jpg)

**Comment by iangilman** [comment]
I see this as well.

**Comment by iangilman** [comment]
I believe #114 fixes this. I'm having trouble testing because the server is being really slow. At any rate, we now get the proper number of tile requests (unlike before).
