### ISSUE TITLE
Does it make sense to add a method here that grabs the "next" and "previous" images to view?

### ISSUE THREAD

**Issue by mejackreed** [sul-dlss/iiifManifestLayouts#79]
This method would look at whether or not paged is active and if so skip to the next/previous "left" page

**Comment by aeschylus** [comment]
Yep, working on it now! :) This will prevent other people from having to do the logic for the book mode, and track the "current page" themselves, which is a bit superfluous. I was thinking I would also add the cycleModes function to the core state as well.

**Comment by aeschylus** [comment]
For example: https://github.com/sul-dlss/sul-embed/issues/433

**Comment by mejackreed** [comment]
Yep exactly what I was working on. Will need to be used in the left/right mouse controls too https://github.com/sul-dlss/sul-embed/pull/437
